---
- hosts: all
  become: yes 
  tasks:
  - name: install webserver on ubuntu
    apt:
    
     name: apache2
     state: present
    
    when: ansible_os_family=="Debian"
  - name: install webserver on redhat
    yum:
     apt:
      name: httpd
      state: present
    when: ansible_os_family=="Redhat"
  - name: to start webserver on ubuntu
    apt:
     name: apache2
     state: started
    when: ansible_os_family=="Debian"
  - name: to start webserver on redhat
    yum:
     name: httpd
     state: started
     
    when: ansible_os_family=="Redhat"