---
- hosts: all
  become: yes
  tasks:
  - name: install java on ubutnuserver
    apt:
      name: "{{myjavapackubuntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: install java on the redhat
    yum:
      name: "{{myjavapackredhat}}"
      state: present
    when: ansible_os_family=="RedHat"
    
